version: '2'
services:
    gisdemo-app:
        image: gisdemo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://gisdemo-mysql:3306/gisdemo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    gisdemo-mysql:
        extends:
            file: mysql.yml
            service: gisdemo-mysql
